name: 'Terraform Apply (main)'

on:
  push:
    branches:
      - main
    paths:
      - 'env/dev/**'
      - '.github/workflows/terraform-apply.yml'

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        run: terraform -chdir=env/dev init

      - name: Terraform Plan
        run: terraform -chdir=env/dev plan

      - name: Terraform Apply
        run: terraform -chdir=env/dev apply -auto-approve
        env: 
          TF_VAR_resource_group_name: ${{ secrets.ARM_RESOURCE_GROUP_NAME }}
          TF_VAR_location: ${{ secrets.ARM_LOCATION }}
          TF_VAR_app_service_plan_name: ${{ secrets.ARM_APP_SERVICE_PLAN_NAME }}
          TF_VAR_frontend_web_app_name: ${{ secrets.ARM_FRONTEND_WEB_APP_NAME }}
          TF_VAR_backend_web_app_name: ${{ secrets.ARM_BACKEND_WEB_APP_NAME }}
          TF_VAR_sql_server_name: ${{ secrets.ARM_SQL_SERVER_NAME }}
          TF_VAR_sql_database_name: ${{ secrets.ARM_SQL_DATABASE_NAME }}
          TF_VAR_sql_admin_username: ${{ secrets.ARM_SQL_ADMIN_NAME }}
          TF_VAR_sql_admin_password: ${{ secrets.ARM_SQL_ADMIN_PASSWORD }}