name: 'Terraform Plan (PR)'

on:
  pull_request:
    paths:
      - 'env/dev/**'
      - '.github/workflows/terraform-plan.yml'

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        run: terraform -chdir=env/dev init

      - name: Terraform Plan
        run: terraform -chdir=env/dev plan -lock=false 